version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: oh-learning-postgres
    environment:
      POSTGRES_USER: oh
      POSTGRES_PASSWORD: oh
      POSTGRES_DB: oh_learning
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oh -d oh_learning"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
